# Generated by Django 3.2.7 on 2021-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='employer_logos'),
        ),
    ]
