# Generated by Django 3.2.7 on 2021-09-04 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cv',
            field=models.FileField(upload_to='users_cvs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
